name: Deno
description: Run the deno CLI
inputs:
    args: 
        description: The arguments to pass to the CLI
        required: true
runs:
    using: docker
    image: hayd/deno:alpine
    args: 
        - ${{fromJSON(inputs.args)}}