name: Deno
description: Run the deno CLI
inputs:
    args: 
        description: The arguments to pass to the CLI
        required: true
runs:
    using: docker
    image: docker://hayd/alpine-deno:latest
    args: 
        - ${{fromJSON(inputs.args)}}